/**
 * One-off script: seeds recurring grocery items for emilioeh1991@gmail.com
 * from the HEB shared shopping list 5f801cdf-5c5c-467a-b443-79db71bad499.
 *
 * Frequency (weeks) picked for a family of 3. Categories use the 19-category
 * H-E-B Manor #811 taxonomy (see scripts/scrape-heb-items.ts).
 *
 * Run: npx tsx scripts/add-heb-recurring-items.ts
 */

import { FirebaseRestService } from '../src/lib/firebase-rest.js'
import type { RecurringGroceryItem } from '../src/lib/types.js'
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const TARGET_EMAIL = 'emilioeh1991@gmail.com'

interface SeedItem {
  name: string
  purchaseAmount: number
  purchaseUnit: string
  category: string
  frequencyWeeks: number
  aisle?: number
  hebPrice?: number
  hebPriceUnit?: string
  storeLocation?: string
  hebSize?: string
}

const ITEMS: SeedItem[] = [
  // --- Bakery & Bread ---
  {
    name: 'H-E-B Bakery Flour Tortillas',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Bakery & Bread',
    frequencyWeeks: 1,
    hebPrice: 4.88,
    hebPriceUnit: 'each',
    hebSize: '20 ct',
    storeLocation: 'On the Right Edge of Bakery',
  },
  {
    name: 'H-E-B Everything Bagels',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Bakery & Bread',
    frequencyWeeks: 2,
    aisle: 4,
    hebPrice: 3.38,
    hebPriceUnit: 'each',
    hebSize: '6 ct',
  },
  {
    name: 'H-E-B Round Top Large White Enriched Sliced Bread',
    purchaseAmount: 1,
    purchaseUnit: 'loaf',
    category: 'Bakery & Bread',
    frequencyWeeks: 2,
    aisle: 4,
    hebPrice: 2.48,
    hebPriceUnit: 'each',
    hebSize: '20 oz',
  },
  {
    name: 'H-E-B 100% Whole Wheat Sliced Bread',
    purchaseAmount: 1,
    purchaseUnit: 'loaf',
    category: 'Bakery & Bread',
    frequencyWeeks: 2,
    aisle: 4,
    hebPrice: 2.68,
    hebPriceUnit: 'each',
    hebSize: '20 oz',
  },
  {
    name: 'Kikkoman Japanese-Style Panko Bread Crumbs',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Baking & Spices',
    frequencyWeeks: 8,
    aisle: 7,
    hebPrice: 2.24,
    hebPriceUnit: 'each',
    hebSize: '8 oz',
  },

  // --- Beverages / Beer & Wine ---
  {
    name: 'Austin Eastciders Cider Variety 12 pk Cans',
    purchaseAmount: 4,
    purchaseUnit: 'pack',
    category: 'Beer & Wine',
    frequencyWeeks: 2,
    aisle: 1,
    hebPrice: 18.27,
    hebPriceUnit: 'each',
    hebSize: '12 pk',
  },
  {
    name: 'Coca-Cola Zero Sugar Soda Fridge Pack 12 pk Cans',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Beverages',
    frequencyWeeks: 2,
    aisle: 11,
    hebPrice: 8.42,
    hebPriceUnit: 'each',
    hebSize: '12 pk',
  },
  {
    name: 'H-E-B Unsweetened Lemon Sparkling Water 12 pk Cans',
    purchaseAmount: 3,
    purchaseUnit: 'pack',
    category: 'Beverages',
    frequencyWeeks: 1,
    aisle: 11,
    hebPrice: 4.25,
    hebPriceUnit: 'each',
    hebSize: '12 pk',
  },
  {
    name: 'H-E-B 100% Orange Juice - No Pulp',
    purchaseAmount: 1,
    purchaseUnit: 'carton',
    category: 'Beverages',
    frequencyWeeks: 2,
    hebPrice: 3.79,
    hebPriceUnit: 'each',
    hebSize: '52 oz',
    storeLocation: 'In Dairy on the Back Wall',
  },
  {
    name: "Independence Coffee Madalyn's Backyard Pecan Whole Bean Coffee",
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Beverages',
    frequencyWeeks: 4,
    aisle: 23,
    hebPrice: 19.98,
    hebPriceUnit: 'each',
    hebSize: '24 oz',
  },

  // --- Dairy & Eggs ---
  {
    name: 'Central Market Organics 2% Reduced Fat Milk',
    purchaseAmount: 3,
    purchaseUnit: 'half gallon',
    category: 'Dairy & Eggs',
    frequencyWeeks: 1,
    hebPrice: 4.04,
    hebPriceUnit: 'each',
    hebSize: '1/2 gal',
    storeLocation: 'In Dairy on the Back Wall',
  },
  {
    name: 'H-E-B Grade AA Cage Free Extra Large Brown Eggs',
    purchaseAmount: 1,
    purchaseUnit: 'carton',
    category: 'Dairy & Eggs',
    frequencyWeeks: 1,
    hebPrice: 4.79,
    hebPriceUnit: 'each',
    hebSize: '18 ct',
    storeLocation: 'In Dairy on the Right Wall',
  },
  {
    name: 'H-E-B Mootopia Lactose-Free Small Curd Cottage Cheese',
    purchaseAmount: 1,
    purchaseUnit: 'tub',
    category: 'Dairy & Eggs',
    frequencyWeeks: 2,
    hebPrice: 2.98,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
    storeLocation: 'In Dairy on the Right Wall',
  },
  {
    name: 'H-E-B Salted Sweet Cream Spreadable Butter',
    purchaseAmount: 1,
    purchaseUnit: 'tub',
    category: 'Dairy & Eggs',
    frequencyWeeks: 3,
    hebPrice: 3.45,
    hebPriceUnit: 'each',
    hebSize: '15 oz',
    storeLocation: 'In Dairy on the Right Wall',
  },
  {
    name: 'H-E-B Sweet Cream Unsalted Butter Sticks',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Dairy & Eggs',
    frequencyWeeks: 4,
    hebPrice: 3.98,
    hebPriceUnit: 'each',
    hebSize: '4 ct',
    storeLocation: 'In Dairy on the Right Wall',
  },
  {
    name: 'H-E-B Whipped Plain Cream Cheese Spread',
    purchaseAmount: 1,
    purchaseUnit: 'tub',
    category: 'Dairy & Eggs',
    frequencyWeeks: 3,
    hebPrice: 2.92,
    hebPriceUnit: 'each',
    hebSize: '12 oz',
    storeLocation: 'In Dairy on the Right Wall',
  },
  {
    name: 'H-E-B Whole Milk Ricotta Cheese',
    purchaseAmount: 1,
    purchaseUnit: 'tub',
    category: 'Dairy & Eggs',
    frequencyWeeks: 4,
    hebPrice: 2.89,
    hebPriceUnit: 'each',
    hebSize: '15 oz',
  },

  // --- Deli & Prepared ---
  {
    name: 'H-E-B Deli Roasted Red Pepper Hummus',
    purchaseAmount: 1,
    purchaseUnit: 'tub',
    category: 'Deli & Prepared',
    frequencyWeeks: 2,
    hebPrice: 4.48,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
    storeLocation: 'Back Edge of Deli',
  },
  {
    name: 'H-E-B Mi Tienda Fully Cooked Barbacoa Seasoned Beef Cheek Meat',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Deli & Prepared',
    frequencyWeeks: 3,
    hebPrice: 15.99,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
    storeLocation: 'Back Edge of Deli',
  },
  {
    name: 'P3 Portable Protein Pack Snack Tray - Turkey, Ham & Cheddar',
    purchaseAmount: 3,
    purchaseUnit: 'each',
    category: 'Deli & Prepared',
    frequencyWeeks: 1,
    hebPrice: 1.96,
    hebPriceUnit: 'each',
    hebSize: '2.3 oz',
  },

  // --- Paper & Household ---
  {
    name: 'Cascade Free & Clear Dishwasher Detergent Liquid Gel',
    purchaseAmount: 1,
    purchaseUnit: 'bottle',
    category: 'Paper & Household',
    frequencyWeeks: 8,
    aisle: 27,
    hebPrice: 9.94,
    hebPriceUnit: 'each',
    hebSize: '75 oz',
  },
  {
    name: 'H-E-B Our Finest Invent-A-Size Paper Towels',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Paper & Household',
    frequencyWeeks: 4,
    aisle: 26,
    hebPrice: 16.29,
    hebPriceUnit: 'each',
    hebSize: '12 Double Rolls',
  },
  {
    name: 'H-E-B Our Finest Ultra Strong Toilet Paper Texas-Size Pack',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Paper & Household',
    frequencyWeeks: 8,
    aisle: 26,
    hebPrice: 29.98,
    hebPriceUnit: 'each',
    hebSize: '36 Mega Rolls',
  },
  {
    name: 'H-E-B Texas Tough Parchment Paper',
    purchaseAmount: 1,
    purchaseUnit: 'roll',
    category: 'Paper & Household',
    frequencyWeeks: 12,
    aisle: 25,
    hebPrice: 2.79,
    hebPriceUnit: 'each',
    hebSize: '45 sq ft',
  },
  {
    name: 'H-E-B Texas Tough Tall Kitchen Flex Trash Bags 13 Gallon',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Paper & Household',
    frequencyWeeks: 8,
    aisle: 25,
    hebPrice: 11.22,
    hebPriceUnit: 'each',
    hebSize: '80 ct',
  },
  {
    name: 'Tide Free & Gentle Liquid Laundry Detergent',
    purchaseAmount: 1,
    purchaseUnit: 'bottle',
    category: 'Paper & Household',
    frequencyWeeks: 8,
    aisle: 28,
    hebPrice: 19.94,
    hebPriceUnit: 'each',
    hebSize: '132 oz',
  },

  // --- Frozen Foods ---
  {
    name: 'Great Catch Frozen Peeled Deveined Tail-Off Large Raw Shrimp',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Frozen Foods',
    frequencyWeeks: 4,
    hebPrice: 13.96,
    hebPriceUnit: 'each',
    hebSize: '2 lbs',
    storeLocation: 'In Seafood on the Left Wall',
  },
  {
    name: 'H-E-B Chicken Bacon Ranch Mac & Cheese Bowl Frozen Meal',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 14,
    hebPrice: 3.98,
    hebPriceUnit: 'each',
    hebSize: '9 oz',
  },
  {
    name: 'H-E-B Frozen Baby Broccoli Florets',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 15,
    hebPrice: 1.98,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
  },
  {
    name: 'H-E-B Frozen Chopped Spinach',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 15,
    hebPrice: 1.26,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
  },
  {
    name: 'H-E-B Frozen Steamable Petite Peas',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 15,
    hebPrice: 1.58,
    hebPriceUnit: 'each',
    hebSize: '12 oz',
  },
  {
    name: 'H-E-B Frozen Steamable Whole Green Beans',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 15,
    hebPrice: 1.48,
    hebPriceUnit: 'each',
    hebSize: '12 oz',
  },
  {
    name: 'H-E-B Frozen Waffles - Buttermilk',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 15,
    hebPrice: 2.15,
    hebPriceUnit: 'each',
    hebSize: '10 ct',
  },
  {
    name: 'H-E-B Poblano Chicken Lasagna Frozen Meal',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 14,
    hebPrice: 3.48,
    hebPriceUnit: 'each',
    hebSize: '11.4 oz',
  },
  {
    name: 'H-E-B Rising Crust Frozen Pizza - Cheese',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 13,
    hebPrice: 4.28,
    hebPriceUnit: 'each',
    hebSize: '28.6 oz',
  },
  {
    name: 'H-E-B Smoked Brisket Mac & Cheese Bowl Frozen Meal',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 14,
    hebPrice: 3.98,
    hebPriceUnit: 'each',
    hebSize: '9 oz',
  },
  {
    name: 'H-E-B Vegetable Lasagna Frozen Meal',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 14,
    hebPrice: 3.48,
    hebPriceUnit: 'each',
    hebSize: '11.4 oz',
  },
  {
    name: "Marie Callender's Chicken Pot Pie",
    purchaseAmount: 2,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    aisle: 14,
    hebPrice: 2.77,
    hebPriceUnit: 'each',
    hebSize: '10 oz',
  },
  {
    name: 'Midtown by H-E-B Amalfi Coast Stone Baked Italian Pizza',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 3,
    aisle: 13,
    hebPrice: 6.48,
    hebPriceUnit: 'each',
    hebSize: '13.8 oz',
  },
  {
    name: 'Midtown by H-E-B Goat Cheese & Roasted Veggie Stone Baked Italian Pizza',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 3,
    aisle: 13,
    hebPrice: 6.48,
    hebPriceUnit: 'each',
    hebSize: '14.8 oz',
  },
  {
    name: 'MightyCrust by H-E-B Italian Sausage & Red Peppers Cauliflower Crust Gluten Free Frozen Pizza',
    purchaseAmount: 1,
    purchaseUnit: 'each',
    category: 'Frozen Foods',
    frequencyWeeks: 3,
    aisle: 13,
    hebPrice: 5.68,
    hebPriceUnit: 'each',
    hebSize: '10.3 oz',
  },
  {
    name: 'Tyson Frozen Baked Chicken Breast Nuggets',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Frozen Foods',
    frequencyWeeks: 2,
    hebPrice: 6.46,
    hebPriceUnit: 'each',
    hebSize: '25 oz',
  },

  // --- Produce ---
  {
    name: 'Fresh Blueberries',
    purchaseAmount: 1,
    purchaseUnit: 'clamshell',
    category: 'Produce',
    frequencyWeeks: 1,
    hebPrice: 4.69,
    hebPriceUnit: 'each',
    hebSize: '11 oz',
  },
  {
    name: 'Fresh Bunch of Bananas',
    purchaseAmount: 1,
    purchaseUnit: 'bunch',
    category: 'Produce',
    frequencyWeeks: 1,
    hebPrice: 1.2,
    hebPriceUnit: 'each',
    hebSize: '~2.4 lbs',
  },
  {
    name: 'Fresh Gala Apples',
    purchaseAmount: 4,
    purchaseUnit: 'each',
    category: 'Produce',
    frequencyWeeks: 1,
    hebPrice: 0.86,
    hebPriceUnit: 'each',
  },
  {
    name: 'Fresh Gold Potatoes',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Produce',
    frequencyWeeks: 2,
    hebPrice: 3.99,
    hebPriceUnit: 'each',
    hebSize: '5 lb bag',
  },
  {
    name: 'Fresh Small Hass Avocado',
    purchaseAmount: 3,
    purchaseUnit: 'each',
    category: 'Produce',
    frequencyWeeks: 1,
    hebPrice: 0.55,
    hebPriceUnit: 'each',
  },
  {
    name: 'Fresh Strawberries',
    purchaseAmount: 1,
    purchaseUnit: 'clamshell',
    category: 'Produce',
    frequencyWeeks: 1,
    hebPrice: 2.29,
    hebPriceUnit: 'each',
    hebSize: '1 lb',
  },
  {
    name: 'H-E-B Mi Tienda Fresh Mexican Mesa Garlic',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Produce',
    frequencyWeeks: 4,
    hebPrice: 2.38,
    hebPriceUnit: 'each',
    hebSize: '3 ct',
  },
  {
    name: 'H-E-B Organics Fresh Baby Spring Mix Lettuce Texas-Size Pack',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Produce',
    frequencyWeeks: 1,
    hebPrice: 4.89,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
    storeLocation: 'In Produce on the Left Wall',
  },
  {
    name: 'H-E-B Texas Roots Fresh Yellow Onions',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Produce',
    frequencyWeeks: 2,
    hebPrice: 2.49,
    hebPriceUnit: 'each',
    hebSize: '3 lb bag',
  },

  // --- Personal Care ---
  {
    name: 'Field & Future by H-E-B Foaming Hand Soap Refill - Lavender & Vanilla',
    purchaseAmount: 1,
    purchaseUnit: 'bottle',
    category: 'Personal Care',
    frequencyWeeks: 6,
    aisle: 34,
    hebPrice: 6.48,
    hebPriceUnit: 'each',
    hebSize: '32 oz',
  },
  {
    name: 'Field & Future by H-E-B Foaming Hand Soap Refill - White Jasmine & Sea Salt',
    purchaseAmount: 1,
    purchaseUnit: 'bottle',
    category: 'Personal Care',
    frequencyWeeks: 6,
    aisle: 34,
    hebPrice: 6.48,
    hebPriceUnit: 'each',
    hebSize: '32 oz',
  },

  // --- Meat / Seafood ---
  {
    name: 'Hill Country Fare Boneless Skinless Chicken Thighs',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Meat',
    frequencyWeeks: 1,
    hebPrice: 10.01,
    hebPriceUnit: 'each',
    hebSize: '~3.11 lbs',
  },
  {
    name: 'H-E-B Natural Applewood Smoked Uncured Bacon',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Meat',
    frequencyWeeks: 2,
    hebPrice: 5.99,
    hebPriceUnit: 'each',
    hebSize: '12 oz',
  },
  {
    name: 'H-E-B Smoked Atlantic Salmon - Traditional',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Seafood',
    frequencyWeeks: 3,
    hebPrice: 6.48,
    hebPriceUnit: 'each',
    hebSize: '4 oz',
  },

  // --- Pantry, Baking & Spices, Canned & Dry Goods, Snacks, Breakfast & Cereal ---
  {
    name: 'Aji-No-Moto MSG Umami Seasoning',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Baking & Spices',
    frequencyWeeks: 16,
    aisle: 5,
    hebPrice: 4.48,
    hebPriceUnit: 'each',
    hebSize: '1 lb',
  },
  {
    name: 'Better Than Bouillon Premium Roasted Beef Base',
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 8,
    aisle: 6,
    hebPrice: 4.82,
    hebPriceUnit: 'each',
    hebSize: '8 oz',
  },
  {
    name: 'Better Than Bouillon Premium Roasted Chicken Base',
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 8,
    aisle: 6,
    hebPrice: 4.82,
    hebPriceUnit: 'each',
    hebSize: '8 oz',
  },
  {
    name: 'Cheez-It Original Cheese Crackers',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Snacks',
    frequencyWeeks: 2,
    aisle: 10,
    hebPrice: 5.97,
    hebPriceUnit: 'each',
    hebSize: '21 oz',
  },
  {
    name: 'Hill Country Fare Pure Baking Soda',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Baking & Spices',
    frequencyWeeks: 16,
    aisle: 7,
    hebPrice: 2.98,
    hebPriceUnit: 'each',
    hebSize: '64 oz',
  },
  {
    name: 'Honey Maid Cinnamon Graham Crackers',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Snacks',
    frequencyWeeks: 3,
    aisle: 10,
    hebPrice: 4.68,
    hebPriceUnit: 'each',
    hebSize: '14.4 oz',
  },
  {
    name: 'H-E-B Angel Hair Capellini Pasta Noodles',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Pantry & Condiments',
    frequencyWeeks: 3,
    aisle: 5,
    hebPrice: 0.98,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
  },
  {
    name: 'H-E-B Enriched Long Grain White Rice',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Pantry & Condiments',
    frequencyWeeks: 4,
    aisle: 5,
    hebPrice: 3.37,
    hebPriceUnit: 'each',
    hebSize: '5 lbs',
  },
  {
    name: 'H-E-B Made in Texas Creamy Peanut Butter',
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 4,
    aisle: 4,
    hebPrice: 3.79,
    hebPriceUnit: 'each',
    hebSize: '28 oz',
  },
  {
    name: 'H-E-B Microwave Popcorn - Butter',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Snacks',
    frequencyWeeks: 3,
    aisle: 10,
    hebPrice: 3.98,
    hebPriceUnit: 'each',
    hebSize: '6 ct',
  },
  {
    name: 'H-E-B Organics Powdered Sugar',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Baking & Spices',
    frequencyWeeks: 12,
    aisle: 7,
    hebPrice: 3.48,
    hebPriceUnit: 'each',
    hebSize: '24 oz',
  },
  {
    name: 'H-E-B Organics Strawberry Fruit Spread',
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 4,
    aisle: 4,
    hebPrice: 4.19,
    hebPriceUnit: 'each',
    hebSize: '17 oz',
  },
  {
    name: 'H-E-B Organics Whole Grain Animal Cookies',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Snacks',
    frequencyWeeks: 2,
    aisle: 10,
    hebPrice: 5.48,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
  },
  {
    name: 'H-E-B Pure Cane Extra Fine Granulated Sugar',
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Baking & Spices',
    frequencyWeeks: 8,
    aisle: 7,
    hebPrice: 2.48,
    hebPriceUnit: 'each',
    hebSize: '2 lbs',
  },
  {
    name: "H-E-B The Baker's Scoop Unbleached All-Purpose Flour",
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Baking & Spices',
    frequencyWeeks: 8,
    aisle: 7,
    hebPrice: 3.78,
    hebPriceUnit: 'each',
    hebSize: '5 lbs',
  },
  {
    name: 'Kikkoman 100% Pure Sesame Oil',
    purchaseAmount: 1,
    purchaseUnit: 'bottle',
    category: 'Pantry & Condiments',
    frequencyWeeks: 12,
    aisle: 5,
    hebPrice: 3.48,
    hebPriceUnit: 'each',
    hebSize: '5 oz',
  },
  {
    name: 'Knox Original Unflavored Gelatine Mix',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Baking & Spices',
    frequencyWeeks: 16,
    aisle: 7,
    hebPrice: 2.74,
    hebPriceUnit: 'each',
    hebSize: '4 ct',
  },
  {
    name: 'Midtown by H-E-B Bronze Cut Penne Rigate Pasta',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Pantry & Condiments',
    frequencyWeeks: 3,
    aisle: 5,
    hebPrice: 1.89,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
  },
  {
    name: 'Midtown by H-E-B Tomato Romano Pasta Sauce',
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 3,
    aisle: 5,
    hebPrice: 4.48,
    hebPriceUnit: 'each',
    hebSize: '16 oz',
  },
  {
    name: 'Nongshim Shin Black Noodle Soup Family Pack',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Canned & Dry Goods',
    frequencyWeeks: 4,
    aisle: 6,
    hebPrice: 8.76,
    hebPriceUnit: 'each',
    hebSize: '4 ct',
  },
  {
    name: 'Nongshim Shin Ramyun Gold Chicken Broth Noodle Soup',
    purchaseAmount: 1,
    purchaseUnit: 'pack',
    category: 'Canned & Dry Goods',
    frequencyWeeks: 4,
    aisle: 6,
    hebPrice: 8.76,
    hebPriceUnit: 'each',
    hebSize: '4 ct',
  },
  {
    name: 'Nutella Hazelnut Spread with Cocoa',
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 4,
    aisle: 4,
    hebPrice: 4.95,
    hebPriceUnit: 'each',
    hebSize: '13 oz',
  },
  {
    name: 'Pearl River Bridge Superior Light Soy Sauce',
    purchaseAmount: 1,
    purchaseUnit: 'bottle',
    category: 'Pantry & Condiments',
    frequencyWeeks: 12,
    aisle: 5,
    hebPrice: 4.84,
    hebPriceUnit: 'each',
    hebSize: '16.9 oz',
  },
  {
    name: "Pirate's Booty Aged White Cheddar Rice & Corn Puffs",
    purchaseAmount: 1,
    purchaseUnit: 'bag',
    category: 'Snacks',
    frequencyWeeks: 3,
    aisle: 9,
    hebPrice: 6.98,
    hebPriceUnit: 'each',
    hebSize: '10 oz',
  },
  {
    name: 'Post Honey Bunches of Oats with Almonds Cereal - Mega Size',
    purchaseAmount: 1,
    purchaseUnit: 'box',
    category: 'Breakfast & Cereal',
    frequencyWeeks: 3,
    aisle: 8,
    hebPrice: 5.97,
    hebPriceUnit: 'each',
    hebSize: '28 oz',
  },
  {
    name: "Rao's Homemade Roasted Garlic Alfredo Sauce",
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 4,
    aisle: 5,
    hebPrice: 6.98,
    hebPriceUnit: 'each',
    hebSize: '15 oz',
  },
  {
    name: "Rao's Homestyle Bolognese Sauce",
    purchaseAmount: 1,
    purchaseUnit: 'jar',
    category: 'Pantry & Condiments',
    frequencyWeeks: 4,
    aisle: 5,
    hebPrice: 6.89,
    hebPriceUnit: 'each',
    hebSize: '24 oz',
  },
]

async function main() {
  console.log(`Seeding ${ITEMS.length} recurring grocery items for ${TARGET_EMAIL}...`)

  const serviceAccountPath = path.resolve(__dirname, '../firebase-service-account.json')
  if (!fs.existsSync(serviceAccountPath)) {
    throw new Error(`Service account not found at: ${serviceAccountPath}`)
  }
  const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf-8'))
  const db = new FirebaseRestService(serviceAccount)

  const users = await db.getCollection('users')
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const targetUser = (users as any[]).find(
    (u) => u.email?.toLowerCase() === TARGET_EMAIL.toLowerCase(),
  )
  if (!targetUser) throw new Error(`User ${TARGET_EMAIL} not found`)

  const scopeId: string = targetUser.familyId || targetUser.id
  const displayName: string = targetUser.displayName || 'User'
  console.log(
    `User ${targetUser.id}, family=${targetUser.familyId || '(none)'}, scopeId=${scopeId}`,
  )

  const collectionPath = `recurring_grocery_items/${scopeId}/items`
  const existing = await db.getCollection<RecurringGroceryItem>(collectionPath)
  const existingByName = new Map(existing.map((i) => [i.name.toLowerCase().trim(), i]))

  let created = 0
  let updated = 0
  let skipped = 0

  for (const item of ITEMS) {
    const key = item.name.toLowerCase().trim()
    const prior = existingByName.get(key)

    if (prior) {
      // Leave existing items alone to avoid clobbering user-tuned frequencies
      skipped++
      console.log(`  SKIP (exists): ${item.name}`)
      continue
    }

    const itemId = `item_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`
    const newItem: RecurringGroceryItem = {
      id: itemId,
      name: item.name,
      purchaseAmount: item.purchaseAmount,
      purchaseUnit: item.purchaseUnit,
      category: item.category,
      frequencyWeeks: item.frequencyWeeks,
      createdAt: new Date().toISOString(),
      addedBy: targetUser.id,
      addedByName: displayName,
      ...(item.aisle !== undefined && { aisle: item.aisle }),
      ...(item.hebPrice !== undefined && { hebPrice: item.hebPrice }),
      ...(item.hebPriceUnit !== undefined && { hebPriceUnit: item.hebPriceUnit }),
    }

    await db.addSubDocument('recurring_grocery_items', scopeId, 'items', itemId, newItem)

    // Product override (aisle, storeLocation, hebSize) — lives in product_overrides/{scopeId}/items
    const overrideKey = item.name.toLowerCase().trim().replace(/\s+/g, '-')
    const override = {
      name: item.name,
      updatedAt: new Date().toISOString(),
      ...(item.aisle !== undefined && { aisle: item.aisle }),
      ...(item.storeLocation && { storeLocation: item.storeLocation }),
      ...(item.hebSize && { hebSize: item.hebSize }),
      ...(item.hebPrice !== undefined && { hebPrice: item.hebPrice }),
      ...(item.hebPriceUnit && { hebPriceUnit: item.hebPriceUnit }),
    }
    if (Object.keys(override).length > 2) {
      await db.setDocument(`product_overrides/${scopeId}/items`, overrideKey, override)
    }

    created++
    console.log(`  +    ${item.name}  (every ${item.frequencyWeeks}w, ${item.category})`)
  }

  console.log(`\nDone. created=${created}, updated=${updated}, skipped=${skipped}`)
}

main().catch((err) => {
  console.error('Error:', err)
  process.exit(1)
})
