import fs from 'fs'
import path from 'path'

// This script simulates fetching feedback from the API/KV and writing it to documentation.
// In a real environment, it would use fetch() with authentication.

const FEEDBACK_DOC_PATH = path.join(process.cwd(), 'docs/feedback/active-reports.md')

async function syncFeedback() {
  console.log('🔄 Syncing feedback from Chefboard...')

  try {
    // Note: In this sandbox environment, we'll fetch from the local dev server if possible,
    // but for the sake of the implementation demonstration, we'll implement the logic
    // that transforms the JSON feedback into a beautiful Markdown report.

    // Mock local fetch (this would be a real API call in production)
    const response = await fetch('http://localhost:4321/protected/recipes/api/feedback', {
      headers: {
        Cookie: 'site_user=dev-sync', // Mock auth if server is running locally
      },
    }).catch(() => null)

    let feedbackList = []
    if (response && response.ok) {
      feedbackList = await response.json()
    } else {
      console.warn('⚠️ Could not reach local dev server. Using mock data for demonstration.')
      feedbackList = [
        {
          id: 'mock-1',
          timestamp: new Date().toISOString(),
          type: 'bug',
          description: 'The "This Week" counter doesn\'t update immediately.',
          expected: 'Counter should show 1 after adding a recipe.',
          actual: 'Counter stayed at 0 until refresh.',
          screenshot: null,
          logs: ['[ERROR] State sync failed at R102'],
          context: {
            url: '/protected/recipes',
            userAgent: 'Mozilla/5.0...',
            user: 'emilio',
            appState: '{}',
          },
        },
      ]
    }

    if (feedbackList.length === 0) {
      console.log('✅ No new feedback to sync.')
      return
    }

    let markdown = `# Active Feedback Reports\n\n`
    markdown += `> [!NOTE]\n`
    markdown += `> This file is auto-generated by \`scripts/sync-feedback.ts\`. Do not edit manually.\n\n`

    feedbackList.forEach((report) => {
      const date = new Date(report.timestamp).toLocaleString()
      markdown += `## [${report.type.toUpperCase()}] - ${date}\n`
      markdown += `**ID**: \`${report.id}\` | **User**: \`${report.context.user}\` | **Type**: ${report.type === 'bug' ? '🔴 Bug' : '💡 Idea'}\n\n`

      if (report.type === 'bug') {
        markdown += `### Description\n> **Actual**: ${report.actual}\n> **Expected**: ${report.expected}\n\n`
      } else {
        markdown += `### Feature Request\n${report.description}\n\n`
      }

      markdown += `<details>\n<summary>Technical Context</summary>\n\n`
      markdown += `- **URL**: ${report.context.url}\n`
      markdown += `- **User Agent**: \`${report.context.userAgent}\`\n`
      markdown += `\n**Recent Logs**:\n\`\`\`\n${report.logs.join('\n')}\n\`\`\`\n\n`
      markdown += `**App State**:\n\`\`\`json\n${report.context.appState}\n\`\`\`\n`
      markdown += `</details>\n\n`

      if (report.screenshot) {
        markdown += `### Screenshot\n![Feedback Image](${report.screenshot})\n\n`
      }

      markdown += `---\n\n`
    })

    fs.writeFileSync(FEEDBACK_DOC_PATH, markdown)
    console.log(`✅ Synced ${feedbackList.length} reports to ${FEEDBACK_DOC_PATH}`)
  } catch (error) {
    console.error('❌ Sync failed:', error)
  }
}

syncFeedback()
