import fs from 'fs'
import path from 'path'
import type { Feedback } from '../src/lib/types'

// This script simulates fetching feedback from the API/KV and writing it to documentation.
// In a real environment, it would use fetch() with authentication.

const FEEDBACK_DOC_PATH = path.join(process.cwd(), 'docs/feedback/active-reports.md')

async function syncFeedback() {
  console.log('🔄 Syncing feedback from Chefboard...')

  try {
    // Note: In this sandbox environment, we'll fetch from the local dev server if possible,
    // but for the sake of the implementation demonstration, we'll implement the logic
    // that transforms the JSON feedback into a beautiful Markdown report.

    // Mock local fetch (this would be a real API call in production)
    const response = await fetch('http://localhost:4321/protected/recipes/api/feedback', {
      headers: {
        Cookie: 'site_user=dev-sync', // Mock auth if server is running locally
      },
    }).catch(() => null)

    let feedbackList: Feedback[] = []
    if (response && response.ok) {
      feedbackList = await response.json()
    } else {
      console.warn('⚠️ Could not reach local dev server. Attempting to fetch from Cloudflare KV...')
      try {
        const { execSync } = await import('child_process')
        // ID is hardcoded for now based on wrangler.toml analysis
        const kvOutput = execSync(
          'npx wrangler kv key get feedback:active --namespace-id 47c74c58b25e4147984b57d677370493 --text --remote',
          { encoding: 'utf-8' },
        )
        feedbackList = JSON.parse(kvOutput)
      } catch (err) {
        console.warn('⚠️ Could not fetch from Cloudflare KV. Using mock data for demonstration.')
        console.error(err)
        feedbackList = [
          {
            id: 'mock-1',
            timestamp: new Date().toISOString(),
            type: 'bug',
            description: 'The "This Week" counter doesn\'t update immediately.',
            expected: 'Counter should show 1 after adding a recipe.',
            actual: 'Counter stayed at 0 until refresh.',
            screenshot: undefined,
            logs: [
              {
                type: 'error',
                args: ['State sync failed at R102'],
                timestamp: new Date().toISOString(),
              },
            ],
            context: {
              url: '/protected/recipes',
              userAgent: 'Mozilla/5.0...',
              user: 'emilio',
              appState: '{}',
            },
          },
        ]
      }
    }

    if (feedbackList.length === 0) {
      console.log('✅ No new feedback to sync.')
      return
    }

    // Ensure images directory exists
    const IMAGES_DIR = path.join(path.dirname(FEEDBACK_DOC_PATH), 'images')
    if (!fs.existsSync(IMAGES_DIR)) {
      fs.mkdirSync(IMAGES_DIR, { recursive: true })
    }

    let markdown = `# Active Feedback Reports\n\n`
    markdown += `> [!NOTE]\n`
    markdown += `> This file is auto-generated by \`scripts/sync-feedback.ts\`. Do not edit manually.\n\n`

    feedbackList.forEach((report: Feedback) => {
      const date = new Date(report.timestamp).toLocaleString()
      markdown += `## [${report.type.toUpperCase()}] - ${date}\n`
      markdown += `**ID**: \`${report.id}\` | **User**: \`${report.context.user}\` | **Type**: ${report.type === 'bug' ? '🔴 Bug' : '💡 Idea'}\n\n`

      if (report.type === 'bug') {
        markdown += `### Description\n> **Actual**: ${report.actual}\n> **Expected**: ${report.expected}\n\n`
      } else {
        markdown += `### Feature Request\n${report.description}\n\n`
      }

      markdown += `<details>\n<summary>Technical Context</summary>\n\n`
      markdown += `- **URL**: ${report.context.url}\n`
      markdown += `- **User Agent**: \`${report.context.userAgent}\`\n`
      if (report.context.windowSize) {
        markdown += `- **Window**: ${report.context.windowSize.width}x${report.context.windowSize.height}\n`
      }
      markdown += `\n**Recent Logs**:\n\`\`\`json\n${JSON.stringify(report.logs, null, 2)}\n\`\`\`\n\n`
      markdown += `**App State**:\n\`\`\`json\n${report.context.appState}\n\`\`\`\n`

      if (report.context.domSnapshot) {
        markdown += `\n<details>\n<summary>DOM Snapshot (HTML)</summary>\n\n\`\`\`html\n${report.context.domSnapshot.slice(0, 10000)}...\n\`\`\`\n*(Truncated for display)*\n</details>\n`
      }

      markdown += `</details>\n\n`

      if (report.screenshot && report.screenshot.startsWith('data:image')) {
        try {
          // Extract base64 data
          const base64Data = report.screenshot.replace(/^data:image\/\w+;base64,/, '')
          const buffer = Buffer.from(base64Data, 'base64')
          const imageFilename = `${report.id}.png`
          const imagePath = path.join(IMAGES_DIR, imageFilename)

          fs.writeFileSync(imagePath, buffer)
          markdown += `### Screenshot\n![Feedback Image](./images/${imageFilename})\n\n`
        } catch (err) {
          console.error(`Failed to save image for report ${report.id}:`, err)
          markdown += `### Screenshot\n> [Error saving image]\n\n`
        }
      } else if (report.screenshot) {
        markdown += `### Screenshot\n![Feedback Image](${report.screenshot})\n\n`
      }

      markdown += `---\n\n`
    })

    fs.writeFileSync(FEEDBACK_DOC_PATH, markdown)
    console.log(`✅ Synced ${feedbackList.length} reports to ${FEEDBACK_DOC_PATH}`)
  } catch (error) {
    console.error('❌ Sync failed:', error)
  }
}

syncFeedback()
