/**
 * Static H-E-B Manor #811 grocery suggestions.
 * Generated by scripts/scrape-heb-items.ts on 2026-04-04.
 * Re-run the script quarterly to refresh prices.
 */

export interface GrocerySuggestion {
  name: string
  brand?: string
  category: string
  /** H-E-B Manor aisle number (undefined for perimeter depts) */
  aisle?: number
  /** Last known H-E-B price */
  hebPrice?: number
  hebPriceUnit?: string
  imageUrl?: string
}

export const GROCERY_SUGGESTIONS: GrocerySuggestion[] = []
