export type CookingStage = 'idle' | 'pre' | 'during' | 'post'
export type HeaderAction =
  | 'delete'
  | 'edit'
  | 'addToWeek'
  | 'move'
  | 'toggleFavorite'
  | 'share'
  | 'refresh'
  | 'history'
