import type { APIRoute } from 'astro'
import { GoogleGenAI, Type as SchemaType } from '@google/genai'

const PROTEIN_OPTIONS = [
  'Chicken',
  'Beef',
  'Pork',
  'Fish',
  'Seafood',
  'Vegetarian',
  'Vegan',
  'Other',
]

const SYSTEM_PROMPT = `
You are an expert Chef and Data Engineer. Your task is to extract structured recipe data from the provided text (webpage) or image.

Return a strict JSON object matching the provided schema.

Rules:
1. If the input is an image, describe what you see and infer the recipe (ingredients/steps) as best as possible.
2. If the input is a URL, parse the HTML.
3. Use reasonable defaults if data is missing (e.g. 2 servings).
4. Identify the "Main Protein Source" and map it strictly to one of these values: ${PROTEIN_OPTIONS.join(', ')}. If unclear, use "Other".
`

export const POST: APIRoute = async ({ request, locals }) => {
  const env = locals.runtime?.env || import.meta.env
  const apiKey = env.GEMINI_API_KEY

  if (!apiKey) {
    return new Response(JSON.stringify({ error: 'Missing API Key configuration' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  try {
    const { url, image } = await request.json()

    if (!url && !image) {
      return new Response(JSON.stringify({ error: 'No input provided' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    let userContentPart: { text?: string; inlineData?: { mimeType: string; data: string } } = {}

    if (url) {
      const siteRes = await fetch(url, {
        headers: {
          'User-Agent':
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        },
      })
      if (!siteRes.ok) throw new Error('Failed to fetch URL')
      const html = await siteRes.text()
      userContentPart = { text: `Source URL: ${url}\n\nHTML Content:\n${html}` }
    } else if (image) {
      // Image is expected to be base64 data URL: "data:image/jpeg;base64,..."
      const base64Data = image.split(',')[1]
      const mimeType = image.split(';')[0].split(':')[1]
      userContentPart = {
        inlineData: {
          mimeType: mimeType,
          data: base64Data,
        },
      }
    }

    const schema = {
      type: SchemaType.OBJECT,
      properties: {
        title: { type: SchemaType.STRING },
        servings: { type: SchemaType.NUMBER },
        prepTime: { type: SchemaType.NUMBER },
        cookTime: { type: SchemaType.NUMBER },
        ingredients: {
          type: SchemaType.ARRAY,
          items: {
            type: SchemaType.OBJECT,
            properties: {
              name: { type: SchemaType.STRING },
              amount: { type: SchemaType.STRING },
              prep: { type: SchemaType.STRING, nullable: true },
            },
            required: ['name', 'amount'],
          },
        },
        steps: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
        notes: { type: SchemaType.STRING, nullable: true },
        protein: {
          type: SchemaType.STRING,
          enum: ['Chicken', 'Beef', 'Pork', 'Fish', 'Seafood', 'Vegetarian', 'Vegan', 'Other'],
        },
        difficulty: { type: SchemaType.STRING },
        cuisine: { type: SchemaType.STRING },
        dietary: { type: SchemaType.ARRAY, items: { type: SchemaType.STRING } },
      },
      required: ['title', 'ingredients', 'steps'],
    }

    const client = new GoogleGenAI({ apiKey })

    const response = await client.models.generateContent({
      model: 'gemini-2.0-flash',
      config: {
        responseMimeType: 'application/json',
        responseSchema: schema,
      },
      contents: [
        {
          role: 'user',
          parts: [{ text: SYSTEM_PROMPT }, userContentPart],
        },
      ],
    })

    const resultText = response.text

    if (!resultText) throw new Error('No content generated by Gemini')

    const recipeData = JSON.parse(resultText)

    // Add source info
    if (url) recipeData.sourceUrl = url
    if (image) recipeData.sourceImage = image

    return new Response(JSON.stringify(recipeData), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    })
  } catch (error: unknown) {
    console.error('Parse Error:', error)
    const message = error instanceof Error ? error.message : 'Failed to process recipe'
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }
}
